
name: 打包并部署到阿里云

on:
  push:
    branches:
      - master
    tags:
      - 'v1.*'
      - 'v0.*'
    paths-ignore:
      - '.github/workflows/*'  # 忽略工作流文件变更

env:
  REGISTRY: crpi-84lajww1vwmf2e1i.cn-hangzhou.personal.cr.aliyuncs.com # 阿里云ACR容器地址
  NAMESPACE: blueskyf # 命名空间
  IMAGE: minecraft # 镜像名
  TAG: ${{ github.sha }}

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: 检出代码
      # if: github.event_name == 'pull_request'
      uses: actions/checkout@v4

    - name: 登入阿里云容器镜像服务
      # if: github.event_name == 'pull_request'
      uses: aliyun/acr-login@v1
      with:
        login-server: "${{ env.REGISTRY }}"
        username: "${{ secrets.REGISTRY_USERNAME }}"
        password: "${{ secrets.REGISTRY_PASSWORD }}"

    - name: 构建并推送镜像到阿里云
      # if: github.event_name == 'pull_request'
      run: |
        docker build --tag "$REGISTRY/$NAMESPACE/$IMAGE:$TAG" .
        docker push "$REGISTRY/$NAMESPACE/$IMAGE:$TAG"

    - name: 阿里云容器镜像安全扫描
      # if: github.event_name == 'pull_request'
      uses: aliyun/acr-scan@v1
      with:
        region-id: "cn-hangzhou"
        access-key-id: "${{ secrets.ACCESS_KEY_ID }}"
        access-key-secret: "${{ secrets.ACCESS_KEY_SECRET }}"
        repository: "${{ env.NAMESPACE }}/${{ env.IMAGE }}"
        tag: "${{ env.TAG }}"

    - name: 通过SSH连接阿里云ECS以部署镜像
      # if: github.event_name == 'push'
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.ECS_HOST }}
        username: ${{ secrets.ECS_USERNAME }}
        password: ${{ secrets.ECS_PASSWORD }}
        script: |
          # 进入工作目录
          cd /minecraft
          
          # 获取最新 docker-compose.yml
          wget -q https://raw.githubusercontent.com/${{ github.repository }}/${{ github.ref_name }}/docker-compose.yml
          
          # 更新环境变量
          echo "REGISTRY=${{ env.REGISTRY }}" > .env
          echo "NAMESPACE=${{ env.NAMESPACE }}" >> .env
          echo "IMAGE=${{ env.IMAGE }}" >> .env
          echo "TAG=${{ env.TAG }}" >> .env

          # 登录阿里云ACR
          echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login -u ${{ secrets.REGISTRY_USERNAME }} ${{ env.REGISTRY }} --password-stdin 
          
          # 拉取最新镜像
          docker pull ${{ env.REGISTRY }}/${{ env.NAMESPACE }}/${{ env.IMAGE }}:${{ env.TAG }}
          
          # 执行
          docker-compose down
          docker-compose pull
          docker-compose up -d
          
          # 清理旧镜像
          docker system prune -af
